import type { ClimateField, PlaceId } from '../types';
import { PLACES } from '../config';
import { fmt, signed } from '../calc';
import { mercator } from '../data/radar';
import { mapBoundaries, mapLabels, projector } from './geography';
import { colorScale, divergingColor, TEMPERATURE_COLORS, ABSOLUTE_TEMPERATURE_COLORS, absoluteTemperatureColor } from './colors';
export type ClimateLayer='change'|'baseline'|'recent';
export function climateMapView(data:ClimateField,layer:ClimateLayer,place:PlaceId,cellIndex:number){
 const automatic=cellIndex<0;
 const extent=[...mercator(10.7,50.8),...mercator(15.7,54)],project=projector(extent,740,600),p=PLACES.find(p=>p.id===place)!;
 if(cellIndex<0){let dist=Infinity;data.cells.forEach((c,i)=>{const lon=c.polygon.reduce((s,p)=>s+p[0],0)/4,lat=c.polygon.reduce((s,p)=>s+p[1],0)/4,d=(lon-p.lon)**2+(lat-p.lat)**2;if(d<dist){dist=d;cellIndex=i;}});}
 const selected=data.cells[cellIndex]??data.cells[0],delta=selected.recent-selected.baseline;
 const field=data.cells.map((c,i)=>{const value=layer==='change'?c.recent-c.baseline:c[layer],color=layer==='change'?divergingColor(value,2.5):absoluteTemperatureColor(value);return `<path data-climate-cell="${i}" d="M ${c.polygon.map(([lon,lat])=>project(lon,lat).map(v=>v.toFixed(1)).join(',')).join(' L ')} Z" fill="${color}" stroke="${color}" stroke-width=".2"><title>${fmt(c.baseline)} → ${fmt(c.recent)} °C · ${signed(c.recent-c.baseline)} °C</title></path>`;}).join('');
 const displayed=layer==='change'?delta:selected[layer];
 const outline=selected.polygon.map(([lon,lat])=>project(lon,lat).join(',')).join(' L ');
 return `<div class="climate-map-heading"><div><span class="eyebrow">HISTORISCHE KLIMAMITTEL</span><h1>${layer==='change'?'Änderung der Jahresmitteltemperatur':'Jahresmitteltemperatur'}</h1></div><div class="climate-layer-tabs" role="group" aria-label="Klima-Kartenebene">${[['change','Änderung'],['baseline','1961–1990'],['recent','1991–2020']].map(([v,label])=>`<button data-climate-layer="${v}" aria-pressed="${layer===v}">${label}</button>`).join('')}</div></div><div class="climate-map-layout"><svg class="climate-field-map" viewBox="0 0 740 600" role="img" aria-label="${data.mode==='demo'?'Synthetische Klimakarte':'DWD-Flächenraster'}: ${layer==='change'?'Temperaturänderung 1991–2020 gegenüber 1961–1990':'langjährige Mitteltemperatur'}"><g class="geo-base">${mapBoundaries(project)}</g><g class="climate-field-cells">${field}</g><g class="geo-outlines">${mapBoundaries(project)}</g><path d="M ${outline} Z" fill="none" stroke="var(--text)" stroke-width="2" pointer-events="none"/>${mapLabels(project,place)}<text x="380" y="50" class="map-direction">N ↑</text></svg><aside class="climate-field-detail"><span class="eyebrow">${automatic?p.name.toUpperCase():'AUSGEWÄHLTE 5-KM-ZELLE'}</span><strong class="field-delta" style="color:${layer==='change'?(delta>=0?'var(--warm)':'var(--cold)'):'var(--temperature-color)'}">${layer==='change'?signed(displayed):fmt(displayed)}<small> °C</small></strong><p>${layer==='change'?'Änderung 1991–2020<br>gegenüber 1961–1990':`Mittlere Jahrestemperatur<br>${layer==='baseline'?'1961–1990':'1991–2020'}`}</p><div class="field-periods"><span>1961–1990<strong>${fmt(selected.baseline)} °C</strong></span><span>1991–2020<strong>${fmt(selected.recent)} °C</strong></span></div>${colorScale(layer==='change'?TEMPERATURE_COLORS:ABSOLUTE_TEMPERATURE_COLORS,layer==='change'?'−2,5 °C':'5 °C',layer==='change'?'+2,5 °C':'13 °C',layer==='change'?'<span class="regular-label">Blau: kühler · Weiß: unverändert · Rot: wärmer. Randfarben auch außerhalb der Skala.</span><span class="small-display-label">Blau kühler · Rot wärmer</span>':'<span class="regular-label">Gemeinsame Temperaturskala für beide Zeiträume.</span><span class="small-display-label">Gleiche Skala beider Zeiträume</span>',layer==='change'?'0':'9 °C')}<p class="map-provenance regular-label">${data.mode==='demo'?'DEMO · erfundene Flächenwerte.':'DWD CDC · aus Stationsmessungen abgeleitet.'}<br>${data.mode==='demo'?'Synthetisches 5-km-Raster für die Gestaltung.':'Raster: 1 km · Anzeige: 5-km-Mittel.'}</p><p class="map-provenance small-display-label">${data.mode==='demo'?'DEMO · synthetische Werte<br>5-km-Raster':'DWD · 5-km-Mittel<br>Aus Stationsmessungen'}</p><small>Historische Mittelwerte, keine Projektion.<br>Für Zellwerte Karte antippen.</small></aside></div>`;
}
