import { fmt, signed } from '../calc';
import { historyReference } from '../data/history';
import type { History } from '../types';
import { divergingColor, TEMPERATURE_COLORS, colorScale } from './colors';
export const anomalyColor=(value:number)=>divergingColor(value,2.5);
export function historyView(data:History,year:number){
 const reference=historyReference(data),selected=data.years.find(y=>y.year===year)??data.years.at(-1)!,start=data.years[0].year,end=data.years.at(-1)!.year;
 const anomalies=data.years.map(y=>y.temperature-reference.temperature),limit=Math.max(2.5,Math.ceil(Math.max(...anomalies.map(Math.abs))*2)/2);
 const x=(i:number)=>70+i/(data.years.length-1)*960,y=(v:number)=>170-v/limit*130,dx=960/(data.years.length-1);
 const band=data.years.map((v,i)=>`<rect x="${x(i)-dx/2}" y="303" width="${dx+.2}" height="12" fill="${anomalyColor(anomalies[i])}" opacity="1"/>`).join('');
 const area=`M ${x(0)},${y(0)} L ${anomalies.map((v,i)=>`${x(i)},${y(v)}`).join(' L ')} L ${x(data.years.length-1)},${y(0)} Z`;
 const smoothed=anomalies.map((_,i)=>i<9?null:anomalies.slice(i-9,i+1).reduce((a,b)=>a+b,0)/10);
 const si=data.years.indexOf(selected),a=anomalies[si];
 const plot=`<svg class="history-chart" viewBox="0 0 1060 355" role="img" aria-label="Temperaturabweichungen ${start} bis ${end}, Blau unter, Rot über dem Mittel 1991–2020"><defs><clipPath id="warm-area"><rect x="0" y="0" width="1060" height="170"/></clipPath><clipPath id="cold-area"><rect x="0" y="170" width="1060" height="185"/></clipPath></defs>${band}<path d="${area}" fill="#df492d" opacity=".6" clip-path="url(#warm-area)"/><path d="${area}" fill="#176ad3" opacity=".65" clip-path="url(#cold-area)"/><line x1="46" x2="1030" y1="170" y2="170" stroke="#647587" stroke-dasharray="4 5"/><path d="M ${anomalies.map((v,i)=>`${x(i)},${y(v)}`).join(' L ')}" stroke="var(--text)" stroke-width="1.7" fill="none"/><path d="M ${smoothed.flatMap((v,i)=>v===null?[]:[`${x(i)},${y(v)}`]).join(' L ')}" stroke="var(--text)" stroke-width="4" fill="none"/>${[-limit,0,limit].map(v=>`<text x="55" y="${y(v)+5}" text-anchor="end">${signed(v)}°</text>`).join('')}${[start,1980,2000,end].map(v=>`<text x="${x(v-start)}" y="341" text-anchor="middle">${v}</text>`).join('')}<line x1="${x(si)}" x2="${x(si)}" y1="24" y2="313" stroke="var(--text)" stroke-width="1"/><circle cx="${x(si)}" cy="${y(a)}" r="6" fill="${a>=0?'var(--warm)':'var(--cold)'}" stroke="var(--bg)" stroke-width="2"/>${data.years.map((v,i)=>`<rect class="year-hit" data-year="${v.year}" x="${x(i)-dx/2}" y="20" width="${dx}" height="300" fill="transparent"><title>${v.year}: ${signed(anomalies[i])} °C</title></rect>`).join('')}</svg>`;
 return `<div class="history-heading"><div><span class="eyebrow">VERGANGENHEIT · ${start}–${end}</span><h1>Jährliche Temperaturabweichung</h1></div><div class="history-trend"><strong style="color:${smoothed.at(-1)!>=0?'var(--warm)':'var(--cold)'}">${signed(smoothed.at(-1)!)}°</strong><span>letzte 10 Jahre<br>zu 1991–2020</span></div></div><div class="history-visual">${plot}</div><div class="history-legend"><span><i class="cold-key"></i><span class="regular-label">Kühler als 1991–2020</span><span class="small-display-label">Kühler</span></span><span><i class="warm-key"></i><span class="regular-label">Wärmer als 1991–2020</span><span class="small-display-label">Wärmer</span></span><span><span class="regular-label">Kräftige Linie: Mittel der jeweils letzten 10 Jahre</span><span class="small-display-label">Linie: 10-Jahres-Mittel</span></span></div><div class="year-explorer"><div class="year-selection"><label for="history-year">Jahr im Detail</label><select id="history-year" aria-label="Historisches Jahr">${data.years.map(v=>`<option value="${v.year}" ${v.year===selected.year?'selected':''}>${v.year}</option>`).join('')}</select></div><div class="year-values"><div><span>Jahresmittel</span><strong>${fmt(selected.temperature)}<small> °C</small></strong><em>${signed(a)} °C zur Referenz</em></div><div><span>Heiße Tage</span><strong>${selected.hotDays}<small> Tage</small></strong><em>Tagesmaximum ≥ 30 °C</em></div><div><span>Niederschlag</span><strong>${fmt(selected.rain,0)}<small> mm</small></strong><em>Jahressumme</em></div></div></div><p class="method-note regular-label">${data.mode==='demo'?'DEMO · synthetische Jahreswerte.':'ERA5-Reanalyse · Messungen und Modellrechnung, keine lokale Stationsmessreihe.'} Jahresabweichung zu 1991–2020. Farbband: −2,5 bis +2,5 °C, Randfarben auch darüber hinaus.</p><p class="method-note small-display-label">${data.mode==='demo'?'DEMO':'ERA5-Reanalyse'} · Abweichung zu 1991–2020</p>`;
}
export function historyIntro(loading:boolean,progress:string){return `<div class="empty-state"><span class="eyebrow">VERGANGENHEIT · ERA5</span><h1>Das Klima im Rückblick</h1><p>Jahreswerte seit 1961 werden automatisch im Hintergrund geladen. Beim ersten Mal dauert dies etwa 1–2 Minuten; danach bleiben sie lokal verfügbar.</p><p class="loading-text" role="status">${loading?progress:'Wartet auf den laufenden Datenabruf …'}</p></div>`;}
