import {weatherFocus} from './weather-focus';
import { moonPage } from './moon';
import { outlookView } from './outlook';
import { weatherIcon } from './weather-icons';
import { berlinDate, clockTime, compass, condition, dateTime, dayLabel, fmt, quantile, signed } from '../calc';
import { BASELINE, CLIMATE_MODELS, FUTURE, PLACES, SCENARIO } from '../config';
import { now } from '../data/api';
import { SEASONS, type Climate, type Ensemble, type PlaceId, type Weather } from '../types';
import { escapeHtml as esc, lineChart, rainChart } from './charts';
import { colorInk, colorScale, divergingColor, RAIN_COLORS } from './colors';
export function empty(message: string, detail:string, action='') { return `<div class="empty-state"><span class="eyebrow">DATENSTATUS</span><h2>${esc(message)}</h2><p>${esc(detail)}</p>${action}</div>`; }
export function weatherView(data:Weather,place:PlaceId,step:number,radar:string,page='overview',week=0,moonDay=0,tiny=false,focusOffset=0,focusCount=7) {
  const p=data.places.find(p=>p.id===place)!;
  const start=Math.max(0,data.time.findIndex(t=>t>=Math.floor(now()/3600)*3600));
  const indices=data.time.map((t,i)=>i>=start&&t<=data.time[start]+48*3600?i:-1).filter(i=>i>=0);
  const selected=indices[Math.min(step,indices.length-1)]??start;
  const t=data.time[selected], current=step===0;
  const temperature=current?p.current.temperature:p.temperature[selected], code=current?p.current.code:p.code[selected];
  const wind=current?p.current.wind:p.wind[selected], direction=current?p.current.direction:p.direction[selected];
  const placeInfo=PLACES.find(x=>x.id===place)!;
  const caption=current?`Aktuell modelliert · ${clockTime(p.current.time)}`:`Modellprognose · ${dateTime(t)}`;
  const today=p.days.find(d=>d.date===berlinDate(t));
  const chartTime=indices.map(i=>data.time[i]);
  const selectedStep=indices.indexOf(selected), pageStart=Math.floor(selectedStep/6)*6;
  const hours=indices.slice(pageStart,pageStart+6);
  const hourRow=`<section class="hourly-forecast"><div class="timeline-head"><strong>48 Stunden · DWD</strong><div class="time-shortcuts"><button data-step="0" class="${current?'active':''}">Jetzt</button><button data-step="24" class="${step===24?'active':''}">+24 h</button><button data-step="48" class="${step===48?'active':''}">+48 h</button></div></div><div class="hour-row" role="group" aria-label="Stundenprognose">${hours.map((i,j)=>`<button class="hour-cell" data-step="${pageStart+j}" aria-pressed="${i===selected}" aria-label="${dateTime(pageStart+j===0?p.current.time:data.time[i])}: ${fmt(pageStart+j===0?p.current.temperature:p.temperature[i])} Grad, Niederschlag ${fmt(p.rain[i])} Millimeter, Wahrscheinlichkeit ${fmt(p.probability[i],0)} Prozent"><span>${pageStart+j===0?'Jetzt':clockTime(data.time[i])}</span>${weatherIcon(pageStart+j===0?p.current.code:p.code[i])}<strong>${fmt(pageStart+j===0?p.current.temperature:p.temperature[i],0)}°</strong><span class="hour-rain">${fmt(p.rain[i])}<small> mm</small></span><span class="hour-probability">${fmt(p.probability[i],0)} %</span></button>`).join('')}</div><div class="hour-pages"><button data-step="${Math.max(0,pageStart-6)}" ${pageStart===0?'disabled':''} aria-label="Vorherige sechs Stunden">←</button><span>${dayLabel(data.time[hours[0]])} · ${clockTime(data.time[hours[0]])}–${clockTime(data.time[hours.at(-1)!])} · Regen mm / %</span><button data-step="${Math.min(indices.length-1,pageStart+6)}" ${pageStart+6>=indices.length?'disabled':''} aria-label="Nächste sechs Stunden">→</button></div></section>`;
  const pages=`<div class="weather-pages" role="group" aria-label="Wetterseiten">${(tiny?[['overview','Übersicht'],['focus','Fokus'],['hours','Stunden'],['days','Tage'],['forecast','Verlauf'],['moon','Mond']]:[['overview','Übersicht'],['focus','Fokus'],['hours','Vorschau'],['forecast','Verlauf'],['moon','Mond']]).map(([id,label])=>`<button data-weather-page="${id}" aria-pressed="${page===id}">${label}</button>`).join('')}</div>`;
  if(page==='focus')return pages+weatherFocus(data,place,radar,focusOffset,focusCount,tiny);
  return `${pages}<div class="weather-overview" data-page="${page}">
    <section class="observation"><div class="eyebrow">${caption}</div><div class="temperature">${fmt(temperature)}<span>°C</span></div><h2 class="current-condition">${weatherIcon(code)}${condition(code)}</h2><p class="place-detail">${placeInfo.detail} · ${placeInfo.lat.toFixed(2)}° N / ${placeInfo.lon.toFixed(2)}° O</p><div class="high-low"><span><small>Max</small> ${fmt(today?.max)}°</span><span><small>Min</small> ${fmt(today?.min)}°</span></div><div class="reading"><span>Wind aus ${compass(direction)}</span><strong>${fmt(wind,0)} <small>km/h</small></strong></div><div class="reading"><span>Niederschlag bis ${clockTime(t)}</span><strong class="blue">${fmt(p.rain[selected])} <small>mm</small></strong></div><div class="reading"><span>Wahrscheinlichkeit</span><strong class="blue">${fmt(p.probability[selected],0)} <small>%</small></strong></div></section>
    ${radar}
    ${hourRow}
    ${outlookView(data,place,week)}
    ${moonPage(now(),moonDay)}
    <section class="forecast-plot"><div class="section-head"><h2>Temperaturverlauf</h2><span>48 Stunden · °C</span></div>${lineChart(chartTime,[{values:indices.map(i=>p.temperature[i]),color:'var(--lime)',name:'Temperatur'}],{selected:Math.min(step,indices.length-1),label:'Temperaturverlauf der kommenden 48 Stunden in Grad Celsius'})}<div class="section-head rain-head"><h3>Niederschlag</h3><span>mm / vorangehende Stunde</span></div>${rainChart(chartTime,indices.map(i=>p.rain[i]))}<div class="chart-dates"><span>${dayLabel(chartTime[0])}</span><span>${dayLabel(chartTime[chartTime.length-1])}</span></div></section>
    <section class="day-row" aria-label="Tagesübersicht"><h2>Nächste Tage</h2>${p.days.filter(d=>d.date>=berlinDate(now())).slice(0,3).map((d,i)=>{const codes=data.time.flatMap((t,j)=>berlinDate(t)===d.date&&p.code[j]!=null?[p.code[j]!]:[]),code=codes.length?Math.max(...codes):null;const low=Math.min(...p.days.flatMap(d=>d.min==null?[]:[d.min])),high=Math.max(...p.days.flatMap(d=>d.max==null?[]:[d.max])),left=d.min==null?0:(d.min-low)/Math.max(1,high-low)*100,width=d.max==null||d.min==null?0:(d.max-d.min)/Math.max(1,high-low)*100;return `<div class="day"><span class="day-title">${i===0?'Heute':i===1?'Morgen':new Intl.DateTimeFormat('de-DE',{weekday:'short',timeZone:'Europe/Berlin'}).format(new Date(d.date+'T12:00:00Z'))}</span><span class="day-symbol">${weatherIcon(code)}<small>${fmt(d.probability,0)} %</small></span><span class="day-low">${fmt(d.min,0)}°</span><span class="day-span"><i style="left:${left}%;width:${width}%"></i></span><strong>${fmt(d.max,0)}°</strong><span class="day-rain">${fmt(d.rain)} mm</span></div>`;}).join('')}</section>
  </div>`;

}
export function compareView(data:Ensemble) {
  const colors=['var(--model-a)','var(--model-b)'];
  return `<div class="view-title"><div><span class="eyebrow">ENSEMBLE-PROGNOSEN</span><h1>Temperatur · Ensemblevergleich</h1></div><span class="unit-tag">Temperatur · 2 m</span></div>
  <div class="compare-legend">${data.series.map((s,i)=>`<div><span class="line-key" style="--key:${colors[i]}"></span><strong>${s.label}</strong><span><span class="regular-label">${s.members} Mitglieder · ${s.resolution}</span><span class="small-display-label">${s.members} Mitglieder</span></span></div>`).join('')}</div>
  <section class="comparison-plot">${lineChart(data.time,data.series.map((s,i)=>({values:s.median,low:s.p10,high:s.p90,color:colors[i],name:s.label,dashed:i===1})),{height:230,intervalSeconds:21600,markers:true,label:'Temperatur-Mediane und 10. bis 90. Perzentile zweier Ensemble-Modelle'})}</section>
  <div class="chart-caption"><span>${dayLabel(data.time[0])} – ${dayLabel(data.time.at(-1)!)}</span><span><span class="regular-label">Alle 6 Stunden · Farben kennzeichnen Modelle</span><span class="small-display-label">6-h-Schritte</span></span></div>
  <p class="comparison-key">Linie: Median · Band: 10.–90. Perzentil je Ensemble</p><div class="comparison-notes"><p><strong>Linie: Median</strong><br>Fläche: 10.–90. Perzentil innerhalb jedes Ensembles. Die Modellstreuung ist kein kalibriertes Konfidenzintervall.</p><p><strong>Modellauflösung</strong><br>ICON-EU-EPS und AIFS haben unterschiedliche Gitter. Die Punktprognosen werden zeitlich angeglichen; sie erhalten keine zusätzliche räumliche Auflösung.</p></div>
  `;

}
export type ClimateMetric = 'temperature' | 'hotDays' | 'rain';
export function climateIntro(loading:boolean,progress:string) { return `<div class="view-title"><div><span class="eyebrow">LANGFRISTIGE ENTWICKLUNG</span><h1>Klimaprojektionen</h1></div></div><div class="periods"><div><span>Referenz</span><strong>${BASELINE.join('–')}</strong></div><span>→</span><div><span>Zukunft</span><strong>${FUTURE.join('–')}</strong></div></div><div class="climate-load"><h2>Vergleich von drei Klimamodellen</h2><p>Mittlere Temperatur, heiße Tage und saisonaler Niederschlag. Es werden ausschließlich vollständige Zeiträume desselben Modells verglichen.</p><p class="scenario">${SCENARIO} · einzig verfügbares Szenario</p><p>Der erste Abruf läuft automatisch im Hintergrund und benötigt etwa 3 Minuten. Danach bleiben die festen Projektionszeiträume dauerhaft gespeichert.</p>${loading?`<p class="loading-text" role="status">${esc(progress)}</p><button class="primary" data-action="cancel-climate">Abruf abbrechen</button>`:'<p class="loading-text">Wartet auf den laufenden Datenabruf …</p>'}</div>`; }
export function climateView(data:Climate,metric:ClimateMetric){
 if(!data.models.length)return empty('Keine vollständigen Klimamodelle','Ein neuer Abruf wird automatisch versucht.');
 const rain=metric==='rain',hot=metric==='hotDays',unit=rain?'mm':hot?'Tage / Jahr':'°C';
 const deltas=data.models.map(m=>rain?0:m.future[metric]-m.baseline[metric]);
 let plot='';
 if(rain){
  const seasons=['Winter','Frühling','Sommer','Herbst'],ds=data.models.flatMap(m=>SEASONS.map(s=>m.future.rain[s]-m.baseline.rain[s])),limit=Math.max(30,Math.ceil(Math.max(...ds.map(Math.abs))/10)*10),y=(v:number)=>135-v/limit*90;
  plot=`<svg class="projection-figure season-overlay" viewBox="0 0 1050 300" role="img" aria-label="Saisonale Niederschlagsänderung; ${data.models.length} Modelle als Punkte je Jahreszeit"><line x1="85" x2="1000" y1="135" y2="135" stroke="#7d8994" stroke-dasharray="4 6"/>${[-limit,0,limit].map(v=>`<text x="85" y="${y(v)+5}" text-anchor="end">${signed(v)} mm</text>`).join('')}${SEASONS.map((season,i)=>{const values=data.models.map(m=>m.future.rain[season]-m.baseline.rain[season]),x=155+i*265;return `<path d="M${x},${y(Math.min(...values))} V${y(Math.max(...values))}" stroke="#99a6b2" stroke-width="20" opacity=".3"/><text x="${x}" y="265" text-anchor="middle">${seasons[i]}</text><text x="${x}" y="290" text-anchor="middle" class="plot-value">${signed(quantile(values,.5)!)} mm</text>`;}).join('')}${data.models.map((m,k)=>`<g class="season-model" data-model="${m.model}">${SEASONS.map((v,i)=>{const x=155+i*265+(k-1)*22,cy=y(m.future.rain[v]-m.baseline.rain[v]),color=m.future.rain[v]>=m.baseline.rain[v]?'var(--wet)':'var(--dry)',title=`${m.model}: ${fmt(m.baseline.rain[v])} → ${fmt(m.future.rain[v])} mm`;return `<g class="season-point" fill="${color}" stroke="var(--bg)" stroke-width="1.5"><title>${title}</title>${k===0?`<circle cx="${x}" cy="${cy}" r="7"/>`:k===1?`<rect x="${x-6}" y="${cy-6}" width="12" height="12"/>`:`<path d="M${x},${cy-8}l8,14h-16Z"/>`}</g>`;}).join('')}</g>`).join('')}</svg><div class="model-keys">${data.models.map((m,i)=>`<span><b class="model-shape">${['●','■','▲'][i]}</b>${m.model.replaceAll('_','-')}</span>`).join('')}</div><p class="chart-caption"><span class="regular-label">Blau / über null: nasser · Braun / unter null: trockener. Grau: Minimum–Maximum; Zahlen: Median der Modelländerungen.</span><span class="small-display-label">Blau nasser · Braun trockener · Spanne: Min–Max</span></p>`;
 }else{
  const maximum=Math.ceil(Math.max(...data.models.flatMap(m=>[m.baseline[metric],m.future[metric]]))+2),minimum=hot?0:Math.floor(Math.min(...data.models.map(m=>m.baseline[metric]))-1),x=(v:number)=>245+(v-minimum)/(maximum-minimum)*655;
  plot=`<div class="climate-summary"><strong style="color:${quantile(deltas,.5)!>=0?'var(--warm)':'var(--cold)'}">${signed(quantile(deltas,.5)!)} <small>${unit}</small></strong><span>Median der Modelländerungen<br>Bandbreite ${signed(Math.min(...deltas))} bis ${signed(Math.max(...deltas))} ${unit}</span></div><svg class="projection-figure" viewBox="0 0 1050 265" role="img" aria-label="Referenz und Zukunft je Klimamodell, gemeinsamer Maßstab">${data.models.map((m,i)=>{const row=42+i*75,a=m.baseline[metric],b=m.future[metric],color=b>=a?'var(--warm)':'var(--cold)';return `<text x="0" y="${row+5}" class="model-name">${m.model.replaceAll('_','-')}</text><line x1="${x(a)}" x2="${x(b)}" y1="${row}" y2="${row}" stroke="${color}" stroke-width="12" opacity=".25"/><circle cx="${x(a)}" cy="${row}" r="8" fill="var(--bg)" stroke="#73869a" stroke-width="3"/><circle cx="${x(b)}" cy="${row}" r="10" fill="${color}"/><text x="${x(a)}" y="${row+29}" text-anchor="middle">${fmt(a)}</text><text x="${x(b)}" y="${row-17}" text-anchor="middle" class="plot-value">${fmt(b)}</text><text x="945" y="${row+5}" fill="${color}">${signed(b-a)} ${hot?'Tage':'°C'}</text>`;}).join('')}${[minimum,(maximum+minimum)/2,maximum].map(v=>`<text x="${x(v)}" y="255" text-anchor="middle">${fmt(v)} ${unit}</text>`).join('')}</svg><div class="history-legend"><span>○ Referenz ${data.baseline.join('–')}</span><span><i class="warm-key"></i>● Zukunft: Zunahme</span><span><i class="cold-key"></i>● Zukunft: Abnahme</span></div>`;
 }
 return `<div class="view-title"><h1>Klimaprojektionen</h1><span class="unit-tag">${data.models.length} / ${CLIMATE_MODELS.length} Modelle</span></div><div class="climate-context"><span>${data.baseline.join('–')} → ${data.future.join('–')}<span class="small-display-label"> · ${data.models.length}/${CLIMATE_MODELS.length} Modelle</span></span><span>${data.scenario}</span></div><div class="metric-tabs" role="group" aria-label="Klimavariable">${[['temperature','Temperatur'],['hotDays','Heiße Tage'],['rain','Niederschlag']].map(([k,label])=>`<button data-metric="${k}" aria-pressed="${metric===k}">${label}</button>`).join('')}</div>${plot}<p class="method-note regular-label">${hot?'Heiße Tage: Tagesmaximum ≥ 30 °C.':rain?'Saisonale Summen, je 20 Jahre. DJF enthält Dezember des Vorjahres.':'Mittlere 2-m-Temperatur, je 20 Jahre.'} Bandbreite = Minimum–Maximum der Modelländerungen, kein Wahrscheinlichkeitsintervall.</p><p class="method-note regular-label">Referenz: Modellsimulation. Zukunft: Klimaprojektion, keine Tagesprognose. ${data.errors.length?esc(data.errors.join(' · ')):''}</p><p class="method-note small-display-label">${hot?'Heiße Tage: ≥ 30 °C · ':''}Modellspanne, keine Wahrscheinlichkeit.${data.errors.length?' Abruf unvollständig.':''}</p>`;
}
export function clockView(weather:Weather|undefined,place:PlaceId) {
  const p=weather?.places.find(p=>p.id===place);
  return `<div class="clock-view"><svg class="clock-face" viewBox="0 0 1160 400" preserveAspectRatio="none" role="img" aria-label="Uhrzeit Europe/Berlin"><text id="clock-large" class="clock-digits" x="580" y="365" text-anchor="middle" textLength="1110" lengthAdjust="spacingAndGlyphs">${clockTime(now())}</text></svg><div class="clock-caption"><p id="clock-date">${new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date())}</p><div class="clock-weather"><span>${PLACES.find(p=>p.id===place)!.name}</span><strong>${fmt(p?.current.temperature)} °C</strong><span>${p?condition(p.current.code):'Keine Wetterdaten'}</span><small>Europe/Berlin</small></div></div></div>`;
}
